name: Build Docker Image

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Log into registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: docker push
        run: |
          docker build --no-cache -t ghcr.io/${{ github.repository_owner }}/code-runner .
          docker push ghcr.io/${{ github.repository_owner }}/code-runner
