name: Build Docker Image

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: docker push
        env:
          DockerPassword: ${{ secrets.PACKAGE_TOKEN }}
        run: |
          docker build --no-cache -t docker.pkg.github.com/naiba/dockerfiles/coderunner .
          docker login -u naiba -p $DockerPassword docker.pkg.github.com
          docker push docker.pkg.github.com/naiba/dockerfiles/coderunner